// QMEC v2 - 250 frases por categorías (50×5) — reajuste 2026-08-25
// Categorías: modismo / refran / pop / anuncio / cancion
// C3: numero real de frases = 250
const FRASES = [
    // ---------------------------------------------------------------------------
    // 1. MODISMOS Y EXPRESIONES HECHAS (50)
    // ---------------------------------------------------------------------------
    { "texto": "Tirar la CASA por la ventana", "categoria": "modismo" },
    { "texto": "Estar a dos VELAS", "categoria": "modismo" },
    { "texto": "Montar un POLLO", "categoria": "modismo" },
    { "texto": "Pagar el PATO", "categoria": "modismo" },
    { "texto": "Cantar las CUARENTA", "categoria": "modismo" },
    { "texto": "Dar la LATA", "categoria": "modismo" },
    { "texto": "Estar como una REGADERA", "categoria": "modismo" },
    { "texto": "Dormir a pierna SUELTA", "categoria": "modismo" },
    { "texto": "Meter la PATA", "categoria": "modismo" },
    { "texto": "Tener mala LECHE", "categoria": "modismo" },
    { "texto": "Ir al GRANO", "categoria": "modismo" },
    { "texto": "Ser la oveja NEGRA", "categoria": "modismo" },
    { "texto": "Poner las CARTAS sobre la mesa", "categoria": "modismo" },
    { "texto": "Andar con pies de PLOMO", "categoria": "modismo" },
    { "texto": "Perder los PAPELES", "categoria": "modismo" },
    { "texto": "Tirar la TOALLA", "categoria": "modismo" },
    { "texto": "Ver las orejas al LOBO", "categoria": "modismo" },
    { "texto": "Estar como un QUESO", "categoria": "modismo" },
    { "texto": "Cortar el BACALAO", "categoria": "modismo" },
    { "texto": "Chuparse los DEDOS", "categoria": "modismo" },
    { "texto": "Costar un OJO de la cara", "categoria": "modismo" },
    { "texto": "Estar sin BLANCA", "categoria": "modismo" },
    { "texto": "Hacerse el SUECO", "categoria": "modismo" },
    { "texto": "No tener PELOS en la lengua", "categoria": "modismo" },
    { "texto": "Echar LEÑA al fuego", "categoria": "modismo" },
    { "texto": "Empinar el CODO", "categoria": "modismo" },
    { "texto": "Estar hasta en la SOPA", "categoria": "modismo" },
    { "texto": "Dar en el CLAVO", "categoria": "modismo" },
    { "texto": "Hacer de TRIPAS corazón", "categoria": "modismo" },
    { "texto": "Me tienes hasta la CORONILLA", "categoria": "modismo" },
    { "texto": "Estar con la mosca detrás de la OREJA", "categoria": "modismo" },
    { "texto": "Buscar tres PIES al gato", "categoria": "modismo" },
    { "texto": "No me des la BRASA", "categoria": "modismo" },
    { "texto": "Hablando del rey de ROMA", "categoria": "modismo" },
    { "texto": "Armarse la MARIMORENA", "categoria": "modismo" },
    { "texto": "Salirse con la SUYA", "categoria": "modismo" },
    { "texto": "Tener memoria de PEZ", "categoria": "modismo" },
    { "texto": "Quedarse en el CHASIS", "categoria": "modismo" },
    { "texto": "Llover a CÁNTAROS", "categoria": "modismo" },
    { "texto": "Faltarle un HERVOR", "categoria": "modismo" },
    { "texto": "Meterse en camisas de once VARAS", "categoria": "modismo" },
    { "texto": "Salirse por la TANGENTE", "categoria": "modismo" },
    { "texto": "Tener la SARTÉN por el mango", "categoria": "modismo" },
    { "texto": "Ver los toros desde la BARRERA", "categoria": "modismo" },
    { "texto": "Estar en el CANDELERO", "categoria": "modismo" },
    { "texto": "Dar la PALIZA", "categoria": "modismo" },
    { "texto": "Ponerse las BOTAS", "categoria": "modismo" },
    { "texto": "Irse por las RAMAS", "categoria": "modismo" },
    { "texto": "Tomar el PELO", "categoria": "modismo" },
    { "texto": "Ser un FANTASMA", "categoria": "modismo" },

    // ---------------------------------------------------------------------------
    // 2. REFRANES Y PROVERBIOS POPULARES (50)
    // ---------------------------------------------------------------------------
    { "texto": "A quien MADRUGA, Dios le ayuda", "categoria": "refran" },
    { "texto": "Más vale PÁJARO en mano que ciento volando", "categoria": "refran" },
    { "texto": "En boca CERRADA no entran moscas", "categoria": "refran" },
    { "texto": "A caballo REGALADO no le mires el diente", "categoria": "refran" },
    { "texto": "Cría CUERVOS y te sacarán los ojos", "categoria": "refran" },
    { "texto": "Aunque la MONA se vista de seda, mona se queda", "categoria": "refran" },
    { "texto": "Ojos que no ven, CORAZÓN que no siente", "categoria": "refran" },
    { "texto": "De tal PALO, tal astilla", "categoria": "refran" },
    { "texto": "El que busca, ENCUENTRA", "categoria": "refran" },
    { "texto": "A buen HAMBRE no hay pan duro", "categoria": "refran" },
    { "texto": "Dime con quién ANDAS y te diré quién eres", "categoria": "refran" },
    { "texto": "La CURIOSIDAD mató al gato", "categoria": "refran" },
    { "texto": "No por mucho madrugar AMANECE más temprano", "categoria": "refran" },
    { "texto": "Zapatero a tus ZAPATOS", "categoria": "refran" },
    { "texto": "El que la SIGUE la consigue", "categoria": "refran" },
    { "texto": "Agua que no has de beber, DÉJALA correr", "categoria": "refran" },
    { "texto": "El MUNDO es un pañuelo", "categoria": "refran" },
    { "texto": "A lo hecho, PECHO", "categoria": "refran" },
    { "texto": "Por la BOCA muere el pez", "categoria": "refran" },
    { "texto": "Al mal tiempo, BUENA cara", "categoria": "refran" },
    { "texto": "Año de NIEVES, año de bienes", "categoria": "refran" },
    { "texto": "Cuando el río suena, AGUA lleva", "categoria": "refran" },
    { "texto": "Del dicho al hecho hay un TRECHO", "categoria": "refran" },
    { "texto": "El que guarda, SIEMPRE tiene", "categoria": "refran" },
    { "texto": "Nadie es PROFETA en su tierra", "categoria": "refran" },
    { "texto": "Quien bien te quiere, te hará LLORAR", "categoria": "refran" },
    { "texto": "Piensa mal y ACERTARÁS", "categoria": "refran" },
    { "texto": "Mucho RUIDO y pocas nueces", "categoria": "refran" },
    { "texto": "Quien tiene boca se EQUIVOCA", "categoria": "refran" },
    { "texto": "Donde las dan, las TOMAN", "categoria": "refran" },
    { "texto": "Quien mucho abarca, POCO aprieta", "categoria": "refran" },
    { "texto": "No hay mal que por bien no VENGA", "categoria": "refran" },
    { "texto": "A la tercera va la VENCIDA", "categoria": "refran" },
    { "texto": "Camarón que se duerme se lo lleva la CORRIENTE", "categoria": "refran" },
    { "texto": "Cada LOCO con su tema", "categoria": "refran" },
    { "texto": "La OCASIÓN la pintan calva", "categoria": "refran" },
    { "texto": "Más vale MAÑA que fuerza", "categoria": "refran" },
    { "texto": "Perro LADRADOR no muerde", "categoria": "refran" },
    { "texto": "En casa del herrero, CUCHILLO de palo", "categoria": "refran" },
    { "texto": "A la vejez, VIRUELAS", "categoria": "refran" },
    { "texto": "Mucha MERMELADA para tan poco pan", "categoria": "refran" },
    { "texto": "A perro FLACO, todo son pulgas", "categoria": "refran" },
    { "texto": "El tiempo todo lo CURA", "categoria": "refran" },
    { "texto": "Quien no arriesga, no GANA", "categoria": "refran" },
    { "texto": "Árbol que nace torcido, jamás su rama ENDEREZA", "categoria": "refran" },
    { "texto": "Donde hay CONFIANZA, da asco", "categoria": "refran" },
    { "texto": "Nadie da DUROS a cuatro pesetas", "categoria": "refran" },
    { "texto": "A rey MUERTO, rey puesto", "categoria": "refran" },
    { "texto": "Las desgracias nunca vienen SOLAS", "categoria": "refran" },
    { "texto": "Quien a buen árbol se arrima, buena SOMBRA le cobija", "categoria": "refran" },

    // ---------------------------------------------------------------------------
    // 3. TV, MEMES Y CULTURA POP (50)
    // ---------------------------------------------------------------------------
    { "texto": "Hasta luego, LUCAS", "categoria": "pop" },
    { "texto": "¿Pero qué INVENTO es este?", "categoria": "pop" },
    { "texto": "Si hay que ir se va, pero ir pa na es TONTERÍA", "categoria": "pop" },
    { "texto": "¡Abracadabra, PATA de cabra!", "categoria": "pop" },
    { "texto": "Un poquito de FAVOR, por favor", "categoria": "pop" },
    { "texto": "¡A jugar, MISTER!", "categoria": "pop" },
    { "texto": "¡Cómo están los MÁQUINAS!", "categoria": "pop" },
    { "texto": "¡Qué fuerte, qué FUERTE!", "categoria": "pop" },
    { "texto": "Te vas a HABER un follón", "categoria": "pop" },
    { "texto": "¡Si me queréis, IRSE!", "categoria": "pop" },
    { "texto": "Yo por mi hija MATO", "categoria": "pop" },
    { "texto": "¡Pim, pam, TOMA Lacasitos!", "categoria": "pop" },
    { "texto": "Súper, dame el MINUTO de oro", "categoria": "pop" },
    { "texto": "¡La que se ha LIADO!", "categoria": "pop" },
    { "texto": "¡Es que me MEO!", "categoria": "pop" },
    { "texto": "¡Anda ya, HOMBRE!", "categoria": "pop" },
    { "texto": "¡Menuda MOVIDA!", "categoria": "pop" },
    { "texto": "¡A la calle, a la CALLE!", "categoria": "pop" },
    { "texto": "¡Eso es verdad verdadera, OYE!", "categoria": "pop" },
    { "texto": "¡Nos van a dar las UVAS!", "categoria": "pop" },
    { "texto": "¡Pero qué DICES, loco!", "categoria": "pop" },
    { "texto": "¡No me cuentes MILONGAS!", "categoria": "pop" },
    { "texto": "¡A otra cosa, MARIPOSA!", "categoria": "pop" },
    { "texto": "¡Aquí se viene a JUGAR!", "categoria": "pop" },
    { "texto": "¡A casita a DORMIR!", "categoria": "pop" },
    { "texto": "¡Pero esto qué ES!", "categoria": "pop" },
    { "texto": "¡Llegar y BESAR el santo!", "categoria": "pop" },
    { "texto": "¡Estar de RODRÍGUEZ!", "categoria": "pop" },
    { "texto": "¡Noches de desenfreno, mañanas de BENADRYL!", "categoria": "pop" },
    { "texto": "¡Sujétame el CUBATA!", "categoria": "pop" },
    { "texto": "¡A tomar por SACO!", "categoria": "pop" },
    { "texto": "¡Madre mía del AMOR hermoso!", "categoria": "pop" },
    { "texto": "¡Me caes como una patata en el ESTÓMAGO!", "categoria": "pop" },
    { "texto": "¡Con la iglesia hemos TOPADO!", "categoria": "pop" },
    { "texto": "¡Me quedado muerta, MARICARMEN!", "categoria": "pop" },
    { "texto": "¡Pasa palabra, COMPAÑERO!", "categoria": "pop" },
    { "texto": "¡Aquí hay mucho MISTERO!", "categoria": "pop" },
    { "texto": "¡Menudo MERENGUE!", "categoria": "pop" },
    { "texto": "¡Ese es mi CHICO!", "categoria": "pop" },
    { "texto": "¡Madre mía, qué JALEO!", "categoria": "pop" },
    { "texto": "¡Qué me estás CONTAINER!", "categoria": "pop" },
    { "texto": "¡A la cueva a DORMIR!", "categoria": "pop" },
    { "texto": "¡No siento las PIERNAS!", "categoria": "pop" },
    { "texto": "¡Hasta la vista, BABY!", "categoria": "pop" },
    { "texto": "¡Que te voted TXAPOTE!", "categoria": "pop" },
    { "texto": "¡Soy un truhán, soy un SEÑOR!", "categoria": "pop" },
    { "texto": "¡Te huelen las SOBACAS!", "categoria": "pop" },
    { "texto": "¡Me resbala todo por la ESPALDA!", "categoria": "pop" },
    { "texto": "¡A la mierda con TODO!", "categoria": "pop" },
    { "texto": "¡Buenas noches y buena SUERTE!", "categoria": "pop" },

    // ---------------------------------------------------------------------------
    // 4. ANUNCIOS COMERCIALES (50)
    // ---------------------------------------------------------------------------
    { "texto": "Busque, COMPARE y si encuentra algo mejor, cómprelo", "categoria": "anuncio" },
    { "texto": "Vuelve a casa por NAVIDAD", "categoria": "anuncio" },
    { "texto": "El frotar se va a ACABAR", "categoria": "anuncio" },
    { "texto": "Porque yo lo VALGO", "categoria": "anuncio" },
    { "texto": "Claro que sí, GUAPI", "categoria": "anuncio" },
    { "texto": "Red Bull te da ALAS", "categoria": "anuncio" },
    { "texto": "Para todo lo demás, MASTERCARD", "categoria": "anuncio" },
    { "texto": "Que el ritmo no PARALICE", "categoria": "anuncio" },
    { "texto": "Hay cosas que el dinero no puede COMPRAR", "categoria": "anuncio" },
    { "texto": "Pezqueñines no, GRACIAS", "categoria": "anuncio" },
    { "texto": "La chispa de la VIDA", "categoria": "anuncio" },
    { "texto": "Guten TAG, soy tu menstruación", "categoria": "anuncio" },
    { "texto": "Bienvenido a la REPÚBLICA independiente de mi casa", "categoria": "anuncio" },
    { "texto": "El turrón más CARO del mundo", "categoria": "anuncio" },
    { "texto": "Leche, cacao, avellanas y AZÚCAR", "categoria": "anuncio" },
    { "texto": "¡Hola, soy EDU, feliz Navidad!", "categoria": "anuncio" },
    { "texto": "Rexona no te ABANDONA", "categoria": "anuncio" },
    { "texto": "A qué huelen las NUBES", "categoria": "anuncio" },
    { "texto": "Cualquier otra cosa es pura IMITACIÓN", "categoria": "anuncio" },
    { "texto": "El secreto está en la MASA", "categoria": "anuncio" },
    { "texto": "Imposible es NADA", "categoria": "anuncio" },
    { "texto": "Just do IT", "categoria": "anuncio" },
    { "texto": "Me gusta CONDUCIR", "categoria": "anuncio" },
    { "texto": "¿Dónde está el BEBÉ?", "categoria": "anuncio" },
    { "texto": "Tómate una Fanta y RÓMPETE el coco", "categoria": "anuncio" },
    { "texto": "Si no hay Casera nos LEVANTAMOS", "categoria": "anuncio" },
    { "texto": "Un punto azul en el OCÉANO", "categoria": "anuncio" },
    { "texto": "Despierta a la VIDA con Nescafé", "categoria": "anuncio" },
    { "texto": "Lo que necesitas es una buena PIZZA", "categoria": "anuncio" },
    { "texto": "¡Qué calor en el TABLADO!", "categoria": "anuncio" },
    { "texto": "Del caserío me FÍO", "categoria": "anuncio" },
    { "texto": "Para la gente NORMAL", "categoria": "anuncio" },
    { "texto": "Y el Madrid, ¿QUÉ?", "categoria": "anuncio" },
    { "texto": "Donuts, ¡anda, los DONUTS!", "categoria": "anuncio" },
    { "texto": "Un poco de MENTOL en el cuerpo", "categoria": "anuncio" },
    { "texto": "Tu otro SEGURO de vida", "categoria": "anuncio" },
    { "texto": "No pesa nada, es LIGERO", "categoria": "anuncio" },
    { "texto": "Todo el mundo tiene un PRECIO", "categoria": "anuncio" },
    { "texto": "Frescor Salvaje de ÁLVAREZ Gómez", "categoria": "anuncio" },
    { "texto": "Soberano es cosa de HOMBRES", "categoria": "anuncio" },
    { "texto": "El algodón no ENGAÑA", "categoria": "anuncio" },
    { "texto": "La batería de DURACELL dura y dura", "categoria": "anuncio" },
    { "texto": "Destapa la FELICIDAD", "categoria": "anuncio" },
    { "texto": "Cacaolat, el mejor BATIDO", "categoria": "anuncio" },
    { "texto": "1880, el turrón más CARO", "categoria": "anuncio" },
    { "texto": "Sabor que APASIONA", "categoria": "anuncio" },
    { "texto": "Todo un lujo a su ALCANCE", "categoria": "anuncio" },
    { "texto": "Piensa en VERDE", "categoria": "anuncio" },
    { "texto": "Fairy, el milagro ANTIGRASA", "categoria": "anuncio" },
    { "texto": "L'Oréal, porque tú lo VALES", "categoria": "anuncio" },

    // ---------------------------------------------------------------------------
    // 5. FRASES DE CANCIONES (50)
    // ---------------------------------------------------------------------------
    { "texto": "Despacito, quiero respirar tu cuello DESPACITO", "categoria": "cancion" },
    { "texto": "A quién le importa lo que yo HAGA", "categoria": "cancion" },
    { "texto": "Tengo el corazón PARTÍO", "categoria": "cancion" },
    { "texto": "Dale a tu cuerpo alegría, MACARENA", "categoria": "cancion" },
    { "texto": "Caminando por la vida, comprendí que lo importante es no MIRAR atrás", "categoria": "cancion" },
    { "texto": "Todos me miran, me miran porque sé que soy BONITA", "categoria": "cancion" },
    { "texto": "Voy a vivir el momento para entender el DESTINO", "categoria": "cancion" },
    { "texto": "Ella perrea sola y no le importa NADIE", "categoria": "cancion" },
    { "texto": "Bailando, me paso el día BAILANDO", "categoria": "cancion" },
    { "texto": "Y cómo es él, en qué lugar se ENAMORÓ de ti", "categoria": "cancion" },
    { "texto": "Resistiré para seguir VIVIENDO", "categoria": "cancion" },
    { "texto": "Amante bandido, nací para SERTÉ fiel", "categoria": "cancion" },
    { "texto": "La barbacoa, la barbacoa, cómo me GUSTA la barbacoa", "categoria": "cancion" },
    { "texto": "La chica de AYER", "categoria": "cancion" },
    { "texto": "Ni tú ni nadie puede CAMBIARME", "categoria": "cancion" },
    { "texto": "Lanza tu perfume al AIRE", "categoria": "cancion" },
    { "texto": "Caminante no hay camino, se hace camino al ANDAR", "categoria": "cancion" },
    { "texto": "Vivo cantando y la vida es un SUEÑO", "categoria": "cancion" },
    { "texto": "Corazón contento, te quiero tanto que no me ENTRA", "categoria": "cancion" },
    { "texto": "Devuélveme a mi CHICA", "categoria": "cancion" },
    { "texto": "Aserejé ja de je tejebe tude JEBERE", "categoria": "cancion" },
    { "texto": "Saber que se puede, querer que se PUEDA", "categoria": "cancion" },
    { "texto": "Bomba, un movimiento sensual, una BOMBA", "categoria": "cancion" },
    { "texto": "Cuéntame cómo te HA ido", "categoria": "cancion" },
    { "texto": "Y voló, y voló, la PALOMA voló", "categoria": "cancion" },
    { "texto": "Tengo la camisa NEGRA", "categoria": "cancion" },
    { "texto": "Un rayo de SOL oh oh oh", "categoria": "cancion" },
    { "texto": "Canta y no LLORES", "categoria": "cancion" },
    { "texto": "Me gustas tú, me gusta la MAÑANA", "categoria": "cancion" },
    { "texto": "Mi gran NOCHE", "categoria": "cancion" },
    { "texto": "En el muelle de SAN Blas", "categoria": "cancion" },
    { "texto": "Si no estás tú, me falta el AIRE", "categoria": "cancion" },
    { "texto": "Lágrimas NEGRAS cayendo por mi rostro", "categoria": "cancion" },
    { "texto": "Bailando con tu SOMBRA", "categoria": "cancion" },
    { "texto": "Danza Kuduro, oy oy OY", "categoria": "cancion" },
    { "texto": "La bilirrubina me sube cuando te VEO", "categoria": "cancion" },
    { "texto": "Ave María, cuándo SERÁS mía", "categoria": "cancion" },
    { "texto": "Vivir así es morir de AMOR", "categoria": "cancion" },
    { "texto": "Suéltate el pelo, ponte los ZAPATOS de tacón", "categoria": "cancion" },
    { "texto": "Como una ola, tu amor llegó a mi VIDA", "categoria": "cancion" },
    { "texto": "Entre el poeta y el PINTOR", "categoria": "cancion" },
    { "texto": "Bailar pegados es BAILAR", "categoria": "cancion" },
    { "texto": "Me pongo fina cuando BAILO", "categoria": "cancion" },
    { "texto": "Sarandonga, nos vamos a COMER", "categoria": "cancion" },
    { "texto": "Qué la detengan, es una MENTIROSA", "categoria": "cancion" },
    { "texto": "Ojalá que llueva CAFÉ en el campo", "categoria": "cancion" },
    { "texto": "Se me enamora el ALMA", "categoria": "cancion" },
    { "texto": "Una rosa es una ROSA", "categoria": "cancion" },
    { "texto": "Lerele lerele, no me des la ESPALDA", "categoria": "cancion" },
    { "texto": "Vuela vuela, no te HACE falta equipaje", "categoria": "cancion" },
];